-- SecureBank - Database Reset
-- WARNING: Destructive. Use only when intentionally resetting the database.

DROP VIEW IF EXISTS v_audit_report CASCADE;
DROP VIEW IF EXISTS v_loan_report CASCADE;
DROP VIEW IF EXISTS v_branch_summary CASCADE;
DROP VIEW IF EXISTS v_transaction_history CASCADE;
DROP VIEW IF EXISTS v_customer_accounts CASCADE;

DROP FUNCTION IF EXISTS sp_transfer(BIGINT, BIGINT, NUMERIC) CASCADE;
DROP FUNCTION IF EXISTS sp_withdraw(BIGINT, NUMERIC) CASCADE;
DROP FUNCTION IF EXISTS sp_deposit(BIGINT, NUMERIC) CASCADE;
DROP FUNCTION IF EXISTS fn_calculate_emi(NUMERIC, NUMERIC, INTEGER) CASCADE;

DROP FUNCTION IF EXISTS fn_prevent_invalid_transaction() CASCADE;
DROP FUNCTION IF EXISTS fn_transaction_audit() CASCADE;

DROP TABLE IF EXISTS suspicious_transactions CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS loans CASCADE;
DROP TABLE IF EXISTS beneficiaries CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
